# Generated by Django 4.2.27 on 2026-01-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='index_number',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='whatsapp_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
