# Generated by Django 4.2.27 on 2026-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='full_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='index_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='whatsapp_number',
            field=models.CharField(max_length=10),
        ),
    ]
